### ISSUE TITLE
Loved your library! Request for Update

### ISSUE THREAD

**Issue by dead8309** [lukeshay/ui#2]
Hi there,

Firstly, I just wanted to express my appreciation for your fantastic library. It has been incredibly useful in my projects, and I'm grateful for the effort you've put into its development.

I wanted to reach out to discuss a KotlinJS wrapper I've created for the Shadcn library. This wrapper relies on your library as a dependency.

I believe an update to your library would greatly benefit the wrapper. If you're open to it, I'd be more than happy to contribute to the update process or assist in any way I can.

Please let me know your thoughts on this matter

**Comment by lukeshay** [comment]
I will update it today
